apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ran-net
  namespace: ran
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ran-net",
      "type": "bridge",
      "bridge": "br0",
      "isGateway": true,
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.8.0/24",
        "rangeStart": "192.168.8.10",
        "rangeEnd": "192.168.8.250",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.8.1"
      }
    }
